# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-29 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login_reg.Users')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='adder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='login_reg.Users'),
        ),
        migrations.AddField(
            model_name='items',
            name='lists',
            field=models.ManyToManyField(related_name='items', to='list_item.Lists'),
        ),
    ]
