# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-29 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=50)),
                ('username', models.CharField(default='no username', max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('passw', models.CharField(default='1234', max_length=50)),
            ],
        ),
    ]
